csvalpha/sofia

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/controllers/activities_controller/create_spec.rb
- spec/controllers/activities_controller/index_spec.rb
- spec/factories/user.rb
- spec/rails_helper.rb
This PR is the initial setup for testing the controllers. It currently only tests the activity index/create methods but the idea is to add more tests later.
> Add basic controller testing

- app/controllers/orders_controller.rb
- spec/controllers/orders_controller/index_spec.rb
Fixes https://github.com/csvalpha/ELISA/issues/9
> Limit order scope in json controller method

- app/javascript/orderscreen/orderhistory.vue
- app/javascript/orderscreen/userselection.vue
- app/javascript/packs/order_screen.js
- app/views/activities/order_screen.html.slim
Some ugly linebreaks were only visible on some 4:3 screens, including the computer at the bar :)
Next up, in a seperate PR, will be a conversion from SLIM to ERB...
Old:
New:
> Fix some errors only occuring on a few screen sizes

- README.md
- lib/omniauth/strategies/banana_oauth2.rb
See: https://github.com/csvalpha/amber-api/pull/85
> Request scope from Banana

- app/views/activities/_edit_modal.html.erb
- app/views/activities/_modal.html.erb
- app/views/credit_mutations/_modal.html.erb
- app/views/price_lists/_modal.html.erb
- app/views/users/_modal.html.erb
- app/views/users/_mutation_modal.html.erb
Dutch and English were mixed in the modals. This PR makes all the labels Dutch, like the placeholders.
> Fix mixed English and Dutch translation

- app/javascript/packs/order_screen.js
- app/views/activities/_edit_modal.html.erb
- app/views/activities/_modal.html.erb
- app/views/activities/order_screen.html.erb
- app/views/activities/show.html.erb
- app/views/credit_mutations/_modal.html.erb
- app/views/price_lists/_modal.html.erb
- app/views/users/_modal.html.erb
- app/views/users/_mutation_modal.html.erb
> Prevent multiple form submits after clicking a submit button multiple times

- app/controllers/payments_controller.rb
- app/views/payments/index.html.erb
This PR improves the layout of the payments page.
Fixes #517
> Improve payment page layout

- app/models/product.rb
- app/views/price_lists/index.html.erb
- spec/models/product_spec.rb
> Make product name immutable

- Dockerfile
Updates the version in the node setup URL to match the major version in .nvmrc.
> Update node setup script to newer version

- Gemfile
- Gemfile.lock
Also see https://stackoverflow.com/a/70500221/4602486
The staging docker container fails to start now with the error `! Unable to load application: LoadError: cannot load such file -- net/pop`
> Add missing net gems

- app/controllers/payments_controller.rb
> Fix 403 when adding payment when not logged in

- app/javascript/packs/order_screen.js
After the flash notifications were fixed, I noticed that they did not account for pin transactions yet. This PR fixes that.
> Fix flash message for pin

- .github/renovate.json
#790 https://docs.renovatebot.com/modules/manager/#extending-a-managers-default-filematch
> fix: html manager fileMatch

- app/views/layouts/application.html.erb
> refactor: change animate.css link to cdnjs

- .github/renovate.json
> fix: move Sentry prBodyNotes to packageRule

- app/controllers/orders_controller.rb
- app/views/activities/order_screen.html.erb
- Hotfix unable to order using pin/cash
- Hotfix pin button without sumup
> Pin related hotfixes

- .github/renovate.json
- app/views/layouts/application.html.erb
- Fixes integrity hash of Sentry script
- Makes Sentry PRs drafts
> Fix sentry integrity hash

- app/controllers/users_controller.rb
- app/models/user.rb
- lib/omniauth/strategies/amber_oauth2.rb
- spec/models/user_spec.rb
Adds nicknames
See https://github.com/csvalpha/amber-api/pull/346 and https://github.com/csvalpha/amber-ui/pull/670
> Add nickname

- app/views/activities/_modal.html.erb
- app/views/credit_mutations/_modal.html.erb
- app/views/credit_mutations/index.html.erb
- app/views/invoices/_modal.html.erb
- app/views/invoices/show.html.erb
- app/views/price_lists/index.html.erb
Some small layout fixes, mainly for mobile devices.
> Layout bugfixes

- app/models/user.rb
- db/migrate/20170922175055_add_user_model.rb
- lib/omniauth/strategies/amber_oauth2.rb
During the connecting of lux ad mosam to an instance of sofia, I found some bugs in our oauth flow. This PR fixes these. See comments below for more details.
> Oauth fixes

- app/models/role.rb
- spec/models/role_spec.rb
Fixes capitalization of role on home screen
> Fix capitalization of role

- .env.example
1. updated the .env.example file to reflect the default behavior of application.rb
This changed fixes amber being stuck trying to redirect the user to sofia
2. Changed the company name so it is UTF-8 compatible, without this change the server would give an error loading the user page due to Expecting UTF-8 but getting ASCII-8BIT. 
With the following command
```
#{Rails.application.config.x.company_name}
````
> Edited the env file

- .github/workflows/publish-image.yml
> Revert "chore(deps): update docker/login-action action to v3" CI Failed

- .github/workflows/continuous-delivery.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/publish-image.yml
`GITHUB_TOKEN` has been able to do this for a while
> refactor: update workflow checks directly

- .env.example
depends on https://github.com/csvalpha/amber-api/pull/478
> Development: default amber-api oauth settings

- .github/workflows/continuous-delivery.yml
> Fix CD error
