lib/omniauth/strategies/banana_oauth2.rb

Since the Oauth changes in Amber we need to request the UI instead of the API so the URL is changed.
Needs: https://github.com/csvalpha/amber-api/pull/52

Do Oauth via Amber-UI

---

bin/ci.sh

Currently the CI is failing due to a CVE in omniauth. Since this vulnerability has no released mitigation we need to do this ourselfs. However, since we only have one oauth provider in use at the moment we do not need to fix this CVE, we can simply ignore it. 
More information in the PR about the issue: https://github.com/omniauth/omniauth/pull/809

Ignore CVE-2015-9284 in audit

---

app/views/credit_mutations/index.html.slim
app/views/users/show.html.slim
config/locales/nl.yml

This PR improves the layout of the mutations page and user mutations table.
Mutations page:
User mutations page:

Mutations layout

---

app/controllers/activities_controller.rb
app/views/activities/show.html.slim

This PR fixes two bugs with the activity locking:
- See #413 
- The success popup is not in Dutch like the rest of the system

Translate success message, only allow treasurer to see locking alert

---

app/views/users/show.html.erb

We missed an `=` in the erb file, which made the credit text not red when it became negative.
Fixe #419

Fix negative credit class

---

app/models/credit_mutation.rb
app/models/product_price.rb
app/views/credit_mutations/_modal.html.erb
config/initializers/simple_form_bootstrap.rb
spec/models/credit_mutation_spec.rb
spec/models/product_price_spec.rb

Fixes #244 
Make the fields `CreditMutation.amount` and `ProductPrice.price` capped by a max to prevent database overflows

Set max amount of money fields

---

config/locales/nl.yml

The streepsysteem ledger code 1400 was an activa while it should be a passiva. A new passiva ledger has been created with the code 0610.

Fix streepsysteem leger code

---

app/views/activities/show.html.erb

In MyFinance the Debit column is on the left and Credit on the right. This PR changes the activity balance view so that it is also shown in this same order.

Swap balance columns

---

app/views/activities/index.html.erb

When an activity is locked it is nice for the treasurer to see this on the Activity index page. This way he/she knows immediately which are still open.

Show lock on Activity.index

---

config/locales/nl.yml

The accounting number was interpreted as an octal number and thus not displayed correctly (displayed as 392). This PR will fix that.

Fix streepsysteem accounting number

---

app/javascript/components/activity/producttotals.vue
app/javascript/components/userinput.vue

The product totals would not show if the filter was empty because that would filter the product totals on orders by the user with the ID 0, which doesn't have any orders (since it doesn't exist). This PR fixes that.

Fix product totals not showing if not filtering

---

app/models/activity.rb
app/models/order.rb
spec/models/activity_spec.rb
spec/models/order_spec.rb

Duplicates were not removed so when a user placed multiple orders he would show up multiple times in the list. This is of course not the intended behaviour.

Remove duplicates in manually_added_users_with_orders

---

app/views/layouts/application.html.erb

By accident the sentry implementation was to always log (also on localhost). This PR fixes that.
The previous sentry commit included the DSN, which could be considered an secret so we should change that one after this PR is merged and deployed

Do not load sentry when on localhost

---

db/migrate/20200324110203_change_product_price_constraint.rb
db/schema.rb

In this commit (https://github.com/csvalpha/sofia/commit/af2226a63faa93def08e3e3af8afa137a344e252) we forgot to add the migration. This causes an issue which was not reproducible on local but did happen on production. This PR fixes the issue by adding the migration.

Add deleted_at index on product_prices table migration

---

.rubocop.yml
app/assets/stylesheets/application.scss
app/controllers/users_controller.rb
app/javascript/components/user/userstable.vue
app/javascript/packs/users.js
app/models/user.rb
app/views/users/index.html.erb
spec/models/user_spec.rb

This PR will add a totals table at the bottom of the users page. This table will show a sum of all the credits of users synched from banana, and all the manually created users with a non-zero credit total. This will make it easy for the treasurer to see if the total credit in SOFIA is equal to the credit in the bookkeeping software. It will also make it easier to check if any manually created accounts still need to receive an invoice.
The Ruby code can probably be nicer, so feel free to improve it :sweat_smile:

Add a users totals table

---

app/views/activities/show.html.erb

Op het moment staat er in de show pagina van de activiteiten 'vergrendeld op', maar als hij dan al eerder vergrendeld is is dat een beetje gek. Heb er nu dus van gemaakt 'Vergrendeld automatisch op', dat maakt het wat duidelijker.

Clarify lock date text

---

app/javascript/packs/activities.js
app/views/activities/_modal.html.erb
app/views/activities/index.html.erb

The activity page was trying to load the priceList dataset, that it didn't had. This causes a error (without an issue on the page itself). This was caused by the fact that the selector of the model on the activity page was the same as the activities page.
https://sentry.io/organizations/csvalpha/issues/1887249022/?project=267713&query=is%3Aunresolved

Fix activity page

---

README.md

We've applied hashing to the amber api so creating the app is a little bit different, so let's make the readme consistent

Make readme consistent with Amber-API

---

package.json
yarn.lock

Webpacker 5.x is not compatible with webpack 5.x yet, so we have to rollback webpack to 4.x. See https://github.com/webpack/webpack/issues/11649#issuecomment-779781768

Rollback webpack from 5.x to 4.x

---

app/controllers/price_lists_controller.rb

There are currently 6 price lists but the last one is not shown. 6 also still fits fine on a normal screen.

Increase number of price lists shown

---

.github/problem-matchers/eslint-stylish.json

Fixes the ESLint problem matcher, apparently the path is /app/app instead of /opt/app.

fix(problem-matchers): match correct path in ESLint matcher

---

app/controllers/activities_controller.rb
app/javascript/packs/order_screen.js
app/views/activities/order_screen.html.erb

iPadOS browsers now 'pretend' to be a desktop browser (i.e. their user agent is the same as that of a MacOS device). This causes the Sumup button to currently not show up on iPads, even though the sumup app is supported for iPads. This PR fixes that by using a [workaroud](https://stackoverflow.com/a/57924983) to check if a device is an iPad.

Fix sumup on iPadOS

---

package.json
yarn.lock

Reverts csvalpha/sofia#738, should resolve #748 until a proper bug fix is found.

revert: chore(deps): update dependency @sentry/browser to v7

---

bin/ci.sh

Although there is something to say for making checks fail when vulnerabilities are present, it also prevents rollout of other important fixes, and sometimes creates conflicts if dependency updates for vulnerabilities are split into multiple PRs.

Allow CI pass with dependency vulnerabilities

---

.github/workflows/continuous-delivery.yml
app/views/partials/_footer.html.erb

Because we are using cloudflare now and can only use one level of subdomains with the free subscription, the staging url has been updated from staging.streep.csvalpha.nl to stagingstreep.csvalpha.nl.

Update staging url

---

app/javascript/packs/order_screen.js

Apparently there are differences between the [iOS](https://github.com/sumup/sumup-ios-url-scheme/blob/master/README.md) and [Android](https://github.com/sumup/sumup-android-api/blob/master/README.md) Sumup APIs, because consistency is way too boring 🙄. This PR makes sure the Sumup app also opens properly with the amount filled in on iOS.

Account for differences in iOS and Android Sumup APIs

---

app/javascript/packs/order_screen.js

Since we're already showing if a payment succeeded in SOFIA (https://github.com/csvalpha/sofia/blob/a93020d6dda0be97e759f1458590661723a4b039/app/controllers/activities_controller.rb#L116), there is no need for the Sumup success screen, it only adds more clicks to the payment process.

Skip success screen

---

app/controllers/activities_controller.rb
app/controllers/credit_mutations_controller.rb
app/controllers/orders_controller.rb
app/javascript/packs/order_screen.js
app/models/order.rb
app/models/user.rb
app/views/activities/order_screen.html.erb
spec/models/order_spec.rb

This PR blocks orders for users with negative credit, if they already had a negative credit at the start of an activity. 
The way this is implemented is by checking if the user already placed an order in that activity before, because he could only have if he had positive credit at the start.
If there are any unclarities or questions about the implementation, please let me know!

Block negative credit orders

---

app/controllers/credit_mutations_controller.rb
app/controllers/orders_controller.rb
app/controllers/users_controller.rb
app/javascript/packs/order_screen.js
app/models/user.rb

Fixes #782 
Reloads the user, and with that his balance and if ordering is allowed, when a user is selected in the orderscreen.

Reload orderscreen credit

---

.github/renovate.json

I noticed renovate did not create PRs for CDN dependency updates (see https://github.com/csvalpha/sofia/blob/587e91359b0afc4d80f8e405c32ebca6026870de/app/views/layouts/application.html.erb#L19). This PR changes the config such that `.html.erb` files are matched by the `html` manager.

Enable renovate for .html.erb files

---

app/controllers/orders_controller.rb
app/jobs/credit_insufficient_notification_job.rb

Since amber users can now no longer order with negative credit at the start of an activity, it is nice if they are notified of their negative credit before the next activity, which is currently not always the case, since mails are always only sent on Thursday. This PR fixes this by sending an email immediately when a user moves from positive to negative credit

Notify amber users of negative credit immediately

---

app/assets/javascripts/application.js
app/views/layouts/application.html.erb
config/initializers/assets.rb
package.json
yarn.lock

Updates Sentry to v7. We can no longer use Sprockets to include Sentry because the node package no longer includes a compiled file.

Update sentry to v7

---

app/mailers/user_credit_mailer.rb
app/views/user_credit_mailer/new_credit_mutation_mail.html.erb

The credit mutation mail currently displays the time at which the email is sent as the time of the credit mutation. Since the mail is queued for asynchronous delivery, this time can be off from the actual time of the mutation. This PR fixes that.

Fix credit mutation time in mail

---

package.json
yarn.lock

Reverts csvalpha/sofia#825
Compilation of vue files is broken after this PR.

Revert "chore(deps): update dependency babel-loader to v9"

---

app/models/product.rb
config/locales/nl.yml
db/seeds/products.rb
spec/factories/product.rb
spec/models/product_spec.rb

We would like to keep track of the craft beer revenue separately from normal beer. This PR adds a new category for that.

Add craft_beer product category

---

app/controllers/activities_controller.rb
app/views/activities/order_screen.html.erb

Fixes #840 
On retrying a transaction, an attempt number is added to the transaction id (e.g. transaction 105 becomes 105-1, 105-2, 105-n on the nth retry)

Fix retry of sumup transaction

---

.gitignore
app/controllers/users_controller.rb
app/javascript/components/user/OrderHistory.vue

Fixes #858 
Table was not sorted because start_time is a ISO 8601 string and not a number, so all the subtractions would return NaN. I changed the code to let the database handle the sorting, which seemed more logical to me.

Fix user order history sorting

---

app/controllers/users_controller.rb

Fixes #850 by excluding the "Streepsysteem Flux" from the accounts to archive.

Fix archiving of flux account

---

.github/workflows/cleanup-registry.yml

`GITHUB_TOKEN` in pipelines can delete package versions on ghcr now, this PR moves the Cleanup Registry workflow to using an official action that also defaults to using this token.

refactor(cleanup-registry): use new action

---

app/mailers/invoice_mailer.rb

Either wicked_pdf or rails updated, which changed the parameters of `render_to_string` in such a way that they only work without file extensions, otherwise it cannot find the templates. When removing the extensions, Sofia no longer shows an error and shows the banner that the invoice was sent succesfully.
I could not test whether the pdf in the sent mail is still correct now, as I could not figure out how to catch sent mails locally.

Fixed error in mailing invoices

---

app/assets/stylesheets/price_lists.scss
app/controllers/price_lists_controller.rb
app/javascript/packs/price_lists.js
app/policies/price_list_policy.rb
app/views/price_lists/index.html.erb
config/routes.rb
db/migrate/20240202124405_add_archived_at_to_price_list.rb
db/schema.rb

The treasurerwanted to be able to see more than 6 pricelists, so the pricelist table at `/price_lists` was made scrollable for that.
To not show old and irrelevant pricelists, the treasurer can now 'archive' pricelists, which simply hides them from the table.
To archive a pricelist, the red circled button in the image below can be pressed:
To view all pricelist, the treasure can check the "Laat gearchieveerde prijslijsten zien" box:
When viewing all pricelists, archived pricelists can be unarchived with the red circled button in the image below:

Made price-lists table scrollable and made lists archivable

---

.github/workflows/continuous-delivery.yml
.github/workflows/continuous-integration.yml
Gemfile
Gemfile.lock
README.md
spec/spec_helper.rb

Adds code coverage reporting with [Codecov](https://about.codecov.io/).
requires https://github.com/csvalpha/sofia/pull/945

feat(tests): add code coverage reporting

---

README.md

if there are any question about why the contents are altered please ask.
I removed the requirement of needing amber-API to log in because this will not be needed in the near future.
fixes https://github.com/csvalpha/sofia/issues/1004 and https://github.com/csvalpha/sofia/issues/910

Update the README to reflect recent changes and added lint & test instructions

---

.github/workflows/continuous-delivery.yml

Previously, changing the secrets in one of the workflows could cause issues when merging into master. This PR resolves those issues by referencing other workflows within the repository instead of the staging ones.
based upon https://docs.github.com/en/actions/sharing-automations/reusing-workflows
fixes https://github.com/csvalpha/sofia/issues/999

Update workflows github
